# Generated by Django 4.2 on 2023-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacher_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=10)),
                ('courseTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmeID', models.CharField(max_length=10)),
                ('programmeName', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(related_name='programmes', to='api.course')),
            ],
        ),
    ]
