# Generated by Django 4.2 on 2023-04-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_course_programme"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="shortProgrammeName",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.programme",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="programmes", to="api.course"
            ),
        ),
    ]
