# Generated by Django 4.2 on 2023-04-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_teacher_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmehead",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.programme",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="courses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
        ),
    ]
