# Generated by Django 4.2 on 2023-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_student_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="courseStartDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="university",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="courseCode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="courseTitle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
