# Generated by Django 4.2 on 2023-04-21 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_course_coursestartdate_student_university_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="courseStartDate",
            new_name="courseStartDateTime",
        ),
    ]
