# Generated by Django 4.2 on 2023-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_rename_coursestartdate_course_coursestartdatetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="courseEndDateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
