# Generated by Django 4.2 on 2023-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_course_courseenddatetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="courses",
        ),
        migrations.AddField(
            model_name="user",
            name="courses",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="courses", to="api.course"
            ),
        ),
    ]
