# Generated by Django 4.2 on 2023-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_remove_student_courses_remove_teacher_courses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="api.course"
            ),
        ),
    ]
