# Generated by Django 4.2 on 2023-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_usercoursetracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercoursetracking",
            name="hours",
        ),
        migrations.AddField(
            model_name="usercoursetracking",
            name="timeTracked",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
