# Generated by Django 4.2 on 2023-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_remove_usercoursetracking_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercoursetracking",
            name="stress",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
