# Generated by Django 4.2 on 2023-04-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_usercoursetracking_stress"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercoursetracking",
            name="userID",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
