# Generated by Django 4.2 on 2023-04-25 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_usercoursetracking_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercoursetracking",
            old_name="userID",
            new_name="user",
        ),
    ]
