# Generated by Django 4.2 on 2023-04-25 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_rename_userid_usercoursetracking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercoursetracking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
