# Generated by Django 4.2 on 2023-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_usercoursetracking_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usercoursetracking",
            constraint=models.UniqueConstraint(
                fields=("user", "course"), name="unique_user_course_combination"
            ),
        ),
    ]
