# Generated by Django 4.2 on 2023-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_usercoursetracking_unique_user_course_combination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercoursetracking",
            name="timeTracked",
        ),
        migrations.AddField(
            model_name="usercoursetracking",
            name="TimeTrackedEnd",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usercoursetracking",
            name="duration",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usercoursetracking",
            name="timeTrackedStart",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
