# Generated by Django 4.2 on 2023-04-25 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_remove_usercoursetracking_timetracked_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercoursetracking",
            old_name="TimeTrackedEnd",
            new_name="timeTrackedEnd",
        ),
    ]
