# Generated by Django 4.2 on 2023-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_rename_timetrackedend_usercoursetracking_timetrackedend"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usercoursetracking",
            name="unique_user_course_combination",
        ),
        migrations.RemoveField(
            model_name="usercoursetracking",
            name="timeTrackedEnd",
        ),
        migrations.RemoveField(
            model_name="usercoursetracking",
            name="timeTrackedStart",
        ),
        migrations.AddConstraint(
            model_name="usercoursetracking",
            constraint=models.UniqueConstraint(
                fields=("user", "course", "date"),
                name="unique_user_course_date_combination",
            ),
        ),
    ]
