# Generated by Django 4.2 on 2023-04-26 13:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_usercoursetracking_unique_user_course_combination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('SEMINAR', 'Seminar'), ('LABB', 'Labb'), ('ASSIGNMENT', 'Assignment'), ('LECTURE', 'Lecture'), ('LESSON', 'Lesson'), ('PRESENTATION', 'Presentation')], max_length=20)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('expectedHours', models.IntegerField(blank=True, null=True)),
                ('dueTime', models.DateTimeField(blank=True, null=True)),
                ('mandatory', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.coursecalendar',),
            managers=[
                ('seminar', django.db.models.manager.Manager()),
            ],
        ),
    ]
