# Generated by Django 4.2 on 2023-05-04 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_remove_question_courseevaluation_delete_answer_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseevaluation",
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="courseevaluation",
            index_together=set(),
        ),
    ]
