# Generated by Django 4.2 on 2023-04-27 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_examination_coursecalendar_eventname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFreetime',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
            ],
        ),
    ]
