# Generated by Django 4.2 on 2023-05-04 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_alter_courseevaluation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseevaluation",
            unique_together={("user", "course")},
        ),
        migrations.AlterIndexTogether(
            name="courseevaluation",
            index_together={("user", "course")},
        ),
    ]
