# Generated by Django 4.2 on 2023-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_excelfile_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseEvent', models.CharField(max_length=50)),
                ('eventStartTime', models.DateTimeField()),
                ('eventEndTime', models.DateTimeField()),
            ],
        ),
    ]
