# Generated by Django 4.2 on 2023-05-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_coursschedule_courseschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.CreateModel(
            name='YearGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearGrade', models.CharField(max_length=10)),
                ('yearGradeClass', models.CharField(max_length=10)),
                ('programme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.programme')),
            ],
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='yearGrade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.yeargrade'),
        ),
    ]
