# Generated by Django 4.2 on 2023-05-08 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_alter_courseevaluation_course_and_more"),
        ("api", "0038_remove_answer_text_answer_number_and_more"),
    ]

    operations = []
