# Generated by Django 4.2 on 2023-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_alter_courseevaluation_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
