# Generated by Django 4.2 on 2023-05-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_course_file_course_filename_courseschedule_course_and_more'),
        ('api', '0040_alter_courseevaluation_course_and_more'),
    ]

    operations = [
    ]
