# Generated by Django 4.2 on 2023-05-09 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_answer_text"),
        ("api", "0041_merge_20230509_1124"),
    ]

    operations = []
