# Generated by Django 4.2 on 2023-05-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_merge_0041_answer_text_0041_merge_20230509_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='yearGrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.yeargrade'),
        ),
    ]
