# Generated by Django 4.2 on 2023-05-11 12:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_student_yeargrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.coursecalendar',),
            managers=[
                ('paper', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.coursecalendar',),
            managers=[
                ('project', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='coursecalendar',
            name='avgHoursDone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecalendar',
            name='eventType',
            field=models.CharField(choices=[('SEMINAR', 'Seminar'), ('LABB', 'Labb'), ('ASSIGNMENT', 'Assignment'), ('PRESENTATION', 'Presentation'), ('EXAMINATION', 'Examination'), ('PROJECT', 'Project'), ('PAPER', 'Paper')], max_length=20),
        ),
    ]
