# Generated by Django 4.2 on 2023-05-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_question_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="courseEvaluation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="api.courseevaluation",
            ),
        ),
    ]
