# Generated by Django 4.2 on 2023-05-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_delete_lecture_delete_lesson_paper_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecalendar',
            name='endDateTime',
        ),
        migrations.AlterField(
            model_name='coursecalendar',
            name='dueTime',
            field=models.DateTimeField(),
        ),
    ]
