# Generated by Django 4.2 on 2023-05-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_coursecalendar_enddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecalendar',
            name='startDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
