# Generated by Django 4.2 on 2023-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_coursecalendar_startdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecalendar',
            name='eventNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecalendar',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
