# Generated by Django 4.2 on 2023-05-10 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_alter_courseevaluation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseevaluation",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
        migrations.AlterField(
            model_name="courseevaluation",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
