# Generated by Django 4.2 on 2023-05-10 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_alter_courseevaluation_course_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseevaluation",
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="courseevaluation",
            index_together=set(),
        ),
    ]
