# Generated by Django 4.2 on 2023-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_alter_courseevaluation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseevaluation",
            name="test",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
