# Generated by Django 4.2 on 2023-05-10 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_courseevaluation_test"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseevaluation",
            unique_together={("user", "course")},
        ),
        migrations.RemoveField(
            model_name="courseevaluation",
            name="test",
        ),
    ]
