# Generated by Django 4.2 on 2023-05-11 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0055_alter_courseevaluation_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseevaluation",
            unique_together={("user", "course")},
        ),
        migrations.AlterIndexTogether(
            name="courseevaluation",
            index_together={("user", "course")},
        ),
    ]
