# Generated by Django 4.2 on 2023-05-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_userschedule'),
        ('api', '0056_alter_courseevaluation_unique_together_and_more'),
    ]

    operations = [
    ]
