# Generated by Django 4.2 on 2023-05-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_merge_20230516_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSchedule',
        ),
    ]
