# Generated by Django 4.2 on 2023-05-18 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0059_userschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="courseTitleEng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usercoursetracking",
            name="duration",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name="usercoursetracking",
            name="stress",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
