# Generated by Django 4.2 on 2023-05-23 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0061_availablehours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="courseTitleEng",
        ),
    ]
