# Generated by Django 4.2 on 2023-05-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_optimalschedule'),
        ('api', '0062_remove_course_coursetitleeng'),
    ]

    operations = [
    ]
