# Generated by Django 4.2 on 2023-04-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseevaluation',
            old_name='stressLevel',
            new_name='stresslevel',
        ),
    ]
