# Generated by Django 4.2 on 2023-04-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_stresslevel_courseevaluation_stresslevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmeID', models.CharField(max_length=10)),
                ('programmeName', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(to='api.course')),
            ],
        ),
    ]
