# Generated by Django 4.2 on 2023-04-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='api.course'),
        ),
    ]
