# Generated by Django 4.2 on 2023-04-11 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='id',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendarID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
